const { Employee } = require("../models");

const EmployeeData = [
  {
    id: 1,
    first_name: "John",
    last_name: "Doe",
    employee_number: 4444,
    site: "San Antonio",
    start_date: 2019 - 04 - 2019,
    role: "CSR",
    language: "SPN",
    group: "A",
    supervisor_id: 1,
    qa_agent: 1,
  },
  {
    id: 2,
    first_name: "Mary",
    last_name: "Jones",
    employee_number: 1345,
    site: "San Antonio",
    start_date: 2019 - 04 - 19,
    role: "CSR",
    language: "ENG",
    group: "A",
    supervisor_id: 1,
    qa_agent: 1,
  },
  {
    id: 3,
    first_name: "Emily",
    last_name: "InParis",
    employee_number: 2354,
    site: "San Antonio",
    start_date: 2021 - 06 - 29,
    role: "CSR",
    language: "ENG",
    group: "A",
    supervisor_id: 1,
    qa_agent: 1,
  },
  {
    id: 4,
    first_name: "Susan",
    last_name: "Gonzalez",
    employee_number: 6597,
    site: "McAllen",
    start_date: 2017 - 02 - 14,
    role: "CSR",
    language: "SPN",
    group: "B",
    supervisor_id: 2,
    qa_agent: 2,
  },
  {
    id: 5,
    first_name: "Betty",
    last_name: "White",
    employee_number: 7989,
    site: "McAllen",
    start_date: 2019 - 04 - 19,
    role: "CSR",
    language: "ENG",
    group: "B",
    supervisor_id: 2,
    qa_agent: 2,
  },
  {
    id: 6,
    first_name: "Leo",
    last_name: "Winslet",
    employee_number: 9898,
    site: "McAllen",
    start_date: 2021 - 05 - 29,
    role: "CSR",
    language: "SPN",
    group: "B",
    supervisor_id: 2,
    qa_agent: 2,
  },
  {
    id: 7,
    first_name: "Jim",
    last_name: "Rodriguez",
    employee_number: 1288,
    site: "Tyler",
    start_date: 2017 - 10 - 29,
    role: "EU",
    language: "SPN",
    group: "A",
    supervisor_id: 3,
    qa_agent: 3,
  },
  {
    id: 8,
    first_name: "Roberto",
    last_name: "Patts",
    employee_number: 8999,
    site: "Tyler",
    start_date: 2020 - 10 - 29,
    role: "EU",
    language: "ENG",
    group: "A",
    supervisor_id: 3,
    qa_agent: 3,
  },
  {
    id: 9,
    first_name: "Kristina",
    last_name: "Steward",
    employee_number: 5413,
    site: "Tyler",
    start_date: 2022 - 01 - 2015,
    role: "EU",
    language: "SPN",
    group: "A",
    supervisor_id: 3,
    qa_agent: 3,
  },
];

const seedPhoneStaff = () => Employee.bulkCreate(EmployeeData);

module.exports = seedPhoneStaff;
